package com.hussienfahmy.core.data.local

import androidx.room.AutoMigration
import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import androidx.room.TypeConverters
import com.hussienfahmy.core.data.local.entity.Grade
import com.hussienfahmy.core.data.local.entity.Semester
import com.hussienfahmy.core.data.local.entity.Subject
import com.hussienfahmy.core.data.local.type_converter.GradeNameTypeConverter

@Database(
    entities = [Subject::class, Grade::class, Semester::class],
    version = 13,
    exportSchema = true,
    autoMigrations = [
        AutoMigration(from = 7, to = 8),
        AutoMigration(from = 8, to = 9),
        AutoMigration(from = 9, to = 10),
        AutoMigration(from = 11, to = 12),
        AutoMigration(from = 12, to = 13),
    ]
)
@TypeConverters(GradeNameTypeConverter::class)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {
    abstract val subjectDao: SubjectDao
    abstract val gradeDao: GradeDao
    abstract val semesterDao: SemesterDao
}

// Generated by Room's KSP compiler as an `actual` on every target (including Android, where it's
// unused since Room falls back to reflection there) - required so the same @Database class also
// compiles for the non-JVM iOS targets, which have no reflection-based instantiation.
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase>